### ISSUE TITLE
Не запускается скрипт MazeSpawner

### ISSUE THREAD

**Issue by Klef99** [BabichMikhail/NTI_TaskC_Maze#1]
(https://user-images.githubusercontent.com/20607279/50428355-6a503b80-08fa-11e9-8ca8-db97558dab37.png)

**Comment by BabichMikhail** [comment]
https://github.com/BabichMikhail/NTI_TaskC_Maze/blob/master/ProjectSettings/ProjectVersion.txt 
Прошу обратить внимание на версию Unity.

**Comment by Klef99** [comment]
Спасибо
